volumes:
  db_data:
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - TZ=${TZ}
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/components.json:/app/components.json
      - ./frontend/index.html:/app/index.html
    command: bun run dev

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - RUST_LOG=${RUST_LOG}
      - PORT=${PORT}
      - SPA_URL=${SPA_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CONSUMER_EMAIL=${CONSUMER_EMAIL}
      - CONSUMER_PASSWORD=${CONSUMER_PASSWORD}
      - REGISTRAR_EMAIL=${REGISTRAR_EMAIL}
      - REGISTRAR_PASSWORD=${REGISTRAR_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - MAIL_URL=${MAIL_URL}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./backend/src:/app/src
    command: cargo run

  db:
    image: postgres:17.6-alpine3.22
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:8.4.0-bookworm
    environment:
      - TZ=${TZ}
    ports:
      - 6377:6379

  mail:
    image: mailhog/mailhog:v1.0.0 
    environment:
      - TZ=${TZ}
    ports:
      - 1025:1025
      - 8025:8025
