FROM rust:slim-trixie

WORKDIR /app

RUN apt update
RUN apt install pkg-config libssl-dev libssl3 ca-certificates -y

COPY Cargo.toml Cargo.lock ./

COPY src ./src
RUN cargo build

CMD ["cargo","run"]
