FROM rust:slim-trixie

WORKDIR /app

COPY Cargo.toml Cargo.lock ./

RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build
RUN rm src/main.rs

COPY src ./src
RUN cargo build

CMD ["cargo","run"]